web_site/News/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DeleteView, UpdateView


from web_site.News.models import NewsArticle
from web_site.News.forms import NewsForm


urlpatterns = patterns("",
    ### News Admin
    ###
    ### View News Articles
    url(r'^$', login_required(ListView.as_view(
        model=NewsArticle,
        template_name="account/news_admins.html")),
        name="admin-display-news"),

    ### Create News Article
    url(r'^add/$', 'web_site.News.views.add_news_item',
        name="admin-add-news"),

    ### Edit News Article -- This may need to be CBV to support cancel
    url(r'^(?P<pk>\d+)/edit/$', login_required(UpdateView.as_view(
        model=NewsArticle,
        form_class=NewsForm,
        success_url=("/account/news"),
        template_name="account/news_admin.html")),
        name="admin-edit-news"),

    ### Delete News Article
    url(r'^(?P<pk>\d+)/delete/$', login_required(DeleteView.as_view(
        model=NewsArticle,
        success_url=('/account/news'))),
        name="admin-delete-news"),

)

web_site/Press/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import ListView, DeleteView, UpdateView
from web_site.Press.models import PressArticle
from web_site.Press.forms import PressArticleForm, PressPageForm
from web_site.Press.views import PagePictureCreateView, PagePictureDeleteView, PageListView, UpdatePageView


urlpatterns = patterns("",
    ### Article admin
    ###
    ### Display Articles
    url(r'^articles$', login_required(ListView.as_view(
        queryset=PressArticle.objects.all().order_by('-year'),
        template_name="account/article_admins.html")),
        name="articles"),
    ### Add Article
    url(r'^article/add/$', 'web_site.Press.views.add_article',
        name="add-article"),
    ### Delete Article
    url(r'^article/delete/(?P<pk>\d+)/$', login_required(DeleteView.as_view(
        model=PressArticle,
        success_url=('/articles'))),
        name="delete-article"),
    ### Edit Article
    url(r'^article/edit/(?P<pk>\d+)/$', login_required(UpdateView.as_view(
        model=PressArticle,
        form_class=PressArticleForm,
        success_url=('/articles'),
        template_name="account/article_admin.html")),
        name="delete-article"),

    ### Article Pages Admin
    ###
    ### Display Article Pages
    url(r'^article/(?P<pk>\d+)/pages/$', login_required(PageListView.as_view(
        template_name="account/article_images.html")),
        name="article-pages"),
    ### Add Page(s) to an Article
    url(r'^article/(?P<pk>\d+)/pages/add/$', login_required(PagePictureCreateView.as_view(),
        {}),
        name="add-article-pages"),
    ### Edit Page to an Article
    url(r'^article/(?P<id>\d+)/pages/page/(?P<pk>\d+)/edit/$', login_required(UpdatePageView.as_view(
        form_class=PressPageForm,
        template_name="account/page_admin.html")),
        name="press-page-edit"),
    ### Delete Page(s) to an Article
    url(r'^article/(?P<id>\d+)/pages/page/(?P<pk>\d+)/delete/$',
        login_required(PagePictureDeleteView.as_view()), {},
            name="press-upload-delete"),
)

web_site/Shop/urls.py
from django.conf.urls import patterns, url
from django.contrib.auth.decorators import login_required
from django.views.generic import DeleteView, UpdateView, CreateView

from web_site.Shop.models import Product, Distributor
from web_site.Shop.forms import ShopProductForm, ShopDistributorForm
from web_site.Shop.views import ProductImageListView, ProductImageDeleteView, ProductImageCreateView


urlpatterns = patterns("",
    ## Display All Products
    url(r'^$', 'web_site.Shop.views.productManagement',
        name="display-products"),
    ## Add a product
    url(r'^add/$', login_required(
        CreateView.as_view(
            model=Product,
            form_class=ShopProductForm,
            success_url=("/account/product"),
            template_name="account/admin_product_distributor_form.html")),
            name="add-product"),
    ## Update a product
    url(r'^edit/(?P<pk>\d+)/$', login_required(
        UpdateView.as_view(
            model=Product,
            form_class=ShopProductForm,
            success_url=("/account/product"),
            template_name="account/admin_product_distributor_form.html")),
            name="update-product"),
    ## Delete a product
    url(r'^delete/(?P<pk>\d+)/$', login_required(
        DeleteView.as_view(
            model=Product,
            success_url=("/account/product"))),
            name="delete-product"),


    url(r'^(?P<pk>\d+)/images/$', login_required(
        ProductImageListView.as_view(
            template_name="account/admin_product_images.html")),
            name="product-images"),
    url(r'^(?P<pk>\d+)/images/add/$', login_required(
        ProductImageCreateView.as_view(),
            {}),
            name="add-product-images"),
    url(r'^(?P<id>\d+)/images/image/(?P<pk>\d+)/delete/$',
        login_required(ProductImageDeleteView.as_view()), {},
            name="product-image-delete"),


    ## Edit a Distributor
    url(r'^distributor/add/$', login_required(
        CreateView.as_view(
            model=Distributor,
            form_class=ShopDistributorForm,
            success_url=("/account/product"),
            template_name="account/admin_distributor_form.html")),
            name="add-distributor"),
    url(r'^distributor/edit/(?P<pk>\d+)/$', login_required(
        UpdateView.as_view(
            model=Distributor,
            form_class=ShopDistributorForm,
            success_url=("/account/product"),
            template_name="account/admin_distributor_form.html")),
            name="create-distributor"),
    url(r'^distributor/delete/(?P<pk>\d+)/$', login_required(
        DeleteView.as_view(
            model=Distributor,
            success_url=("/account/product"))),
            name="delete-distributor"),
)

web_site/urls.py
from django.conf import settings
from django.conf.urls import patterns, include, url
from django.conf.urls.static import static
from django.views.generic import UpdateView
from django.contrib.auth.decorators import login_required
from django.views.generic.simple import direct_to_template
from web_site.UserProfile.forms import ArtistPictureForm
from web_site.UserProfile.views import (PictureCreateView, PictureDeleteView,
        PublicGetArtistImages, DisplayAristImagesAdmin)
from web_site.UserProfile.models import Picture
from web_site.Shop.models import Product
from web_site.Shop.views import viewProduct
from django.contrib import admin
admin.autodiscover()


urlpatterns = patterns("",
    url(r"^$", direct_to_template, {"template": "homepage.html"},
        name="home"),
    url(r"^shop/$", 'web_site.Carousel.views.ShopHomePage',
        name="shop-home"),
    url(r"^community/$", 'web_site.Community.views.showCommunity',
        name="community"),
    url(r"^artists/(?P<slug>[-\w\d]+)/$", PublicGetArtistImages.as_view(
        template_name="artist-homepage.html"),
        name="artists"),
    url(r"^press/$", 'web_site.Press.views.displayPressArticles',
        name="press"),
    url(r"^news/$", 'web_site.News.views.displayNewsItems',
        name="news"),
    url(r'^product/$', 'web_site.Shop.views.displayMerchandise',
        name="merchandise"),
    url(r'^product/(?P<slug>[-\w\d]+)/$', viewProduct.as_view(
        model=Product,
        template_name="merchandise-item-homepage.html"),
        name="product-page"),

    ### User Images accountin
    url(r'^account/images/$', login_required(
        DisplayAristImagesAdmin.as_view(
        template_name="account/account_images.html")),
        name="manage-artist-images"),

    ### Add Account Image
    url(r'^account/images/add/$', login_required(
        PictureCreateView.as_view()),
        name="upload-artist-images"),
    ### Delete Account Image
    url(r'^account/images/delete/(?P<pk>\d+)$',
        login_required(PictureDeleteView.as_view()),
        name="delete-artist-images"),

    ### Edit an Artist's Image
    url(r'^account/images/edit/(?P<pk>\d+)$', login_required(
        UpdateView.as_view(
        model=Picture,
        form_class=ArtistPictureForm,
        success_url=("/account/images"),
        template_name="account/artist_images_admin.html")),
        name="admin-artist-image-edit"),




    url(r"^account/community/", include("web_site.Community.urls")),
    url(r"^account/press/", include("web_site.Press.urls")),
    url(r"^account/news/", include("web_site.News.urls")),
    url(r"^account/artists/", include("web_site.UserProfile.urls")),
    url(r"^account/product/", include('web_site.Shop.urls')),
    url(r"^account/carousel/", include('web_site.Carousel.urls')),



    ### Redactor.js WYSIWYG Editor
    ###
    url(r"^uploads/$", "web_site.News.views.upload_photos",
        name="upload_photos"),
    url(r"^recent/$", "web_site.News.views.recent_photos",
        name="recent_photos"),


    ### admin
    url(r"^admin/", include(admin.site.urls)),

    url(r"^account/", include("account.urls")),

)

import os
urlpatterns += patterns('',
    (r'^media/(.*)$',
        'django.views.static.serve',
            {'document_root':
            os.path.join(os.path.abspath(os.path.dirname(__file__)),
                'media')}),
)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

web_site/Community/models.py
from django.db import models
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django_thumbs.db.models import ImageWithThumbsField
from south.modelsinspector import add_introspection_rules

add_introspection_rules(
    [
        (
            (ImageWithThumbsField, ),
            [],
            {
                "verbose_name": ["verbose_name", {"default": None}],
                "name":         ["name",         {"default": None}],
                "width_field":  ["width_field",  {"default": None}],
                "height_field": ["height_field", {"default": None}],
                "sizes":        ["sizes",        {"default": None}],
            },
        ),
    ],
    ["^django_thumbs.db.models", ])


class CommunityEvent(models.Model):
    title = models.CharField(max_length=50, blank=True, null=True)
    description = models.TextField()

    class Meta:
        ordering = ['-id']

    def __unicode__(self):
        return '%s' % (self.title)


class CommunityPicture(models.Model):
    event = models.ForeignKey(CommunityEvent)
    file = ImageWithThumbsField(upload_to="community", sizes=((125, 125), (250, 250), (640, 427),))
    slug = models.SlugField(max_length=50, blank=True)

    def __unicode__(self):
        return '%s' '%s' % (self.event, self.file)

    @models.permalink
    def get_absolute_url(self):
        return('admin-community-images', {
            'pk': self.event.id
            })

    def save(self, *args, **kwargs):
        self.slug = self.file.name
        super(CommunityPicture, self).save(*args, **kwargs)

    def delete(self, *args, **kwargs):
        self.file.delete(False)
        super(CommunityPicture, self).delete(*args, **kwargs)


class CommunityPictureForm(forms.ModelForm):
    class Meta:
        model = CommunityPicture
        fields = ['file', ]

    def UploadImage(request):
        """Upload Images"""
        if request.method == 'POST':
            form = CommunityPictureForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.event = form.kwargs['pk']
                obj.save()
                return HttpResponseRedirect(".")
        else:
            form = CommunityPictureForm()
        template = "picture_form.html"
        data = {
            'form': form,
        }
        return render_to_response(template, data, context_instance=RequestContext(request))

web_site/Press/models.py
from django.db import models
from django import forms
from django.http import HttpResponseRedirect
from django.shortcuts import render_to_response
from django.template.context import RequestContext
from django.utils.translation import ugettext_lazy as _
from django_thumbs.db.models import ImageWithThumbsField

from south.modelsinspector import add_introspection_rules

add_introspection_rules(
    [
        (
            (ImageWithThumbsField, ),
            [],
            {
                "verbose_name": ["verbose_name", {"default": None}],
                "name":         ["name",         {"default": None}],
                "width_field":  ["width_field",  {"default": None}],
                "height_field": ["height_field", {"default": None}],
                "sizes":        ["sizes",        {"default": None}],
            },
        ),
    ],
    ["^django_thumbs.db.models", ])


class PressArticle(models.Model):
    title = models.CharField(_("Title"), max_length=255, null=True, blank=True)
    publication = models.CharField(_("Publication"), max_length=255, null=True,
        blank=True, unique=True)
    year = models.PositiveSmallIntegerField(_("Year"), max_length=4, null=False, blank=False)
    thumbnail = ImageWithThumbsField(_("thumbnail"), upload_to="images/",
        blank=True, null=True, sizes=((125, 125), (250, 250), (640, 427),))

    class Meta:
        ordering = ['-year']

    def __unicode__(self):
        return "'%s' - '%s'" % (self.title, self.publication)


class PressPage(models.Model):
    article = models.ForeignKey(PressArticle)
    file = ImageWithThumbsField(upload_to="images/", sizes=((125, 125), (250, 250), (640, 427),))
    slug = models.SlugField(max_length=50, blank=True)
    pgnumber = models.PositiveSmallIntegerField(null=True,
        blank=True)

    class Meta:
        ordering = ['pgnumber']

    def __unicode__(self):
        return '%s' '%s' '%s' % (self.article, self.file, self.pgnumber)

    @models.permalink
    def get_absolute_url(self, *args, **kwargs):
        return('article-pages', (), {
            'pk': self.article.id
            })

        def save(self, *args, **kwargs):
            self.slug = self.file.name
            super(PressPage, self).save(*args, **kwargs)

        def delete(self, *args, **kwargs):
            self.file.delete(False)
            super(PressPage, self).delete(*args, **kwargs)


class PressPageForm(forms.ModelForm):
    class Meta:
        model = PressPage
        fields = ['file', ]

    def UploadImage(request):
        """Upload Images"""
        if request.method == 'POST':
            form = PressPageForm(request.POST, request.FILES)
            if form.is_valid():
                obj = form.save(commit=False)
                obj.article = form.kwargs['pk']
                obj.pgnumber = 1
                obj.save()
                return HttpResponseRedirect(".")
        else:
            form = PressPageForm()
        template = "presspage_form.html"
        data = {
            'form': form,
        }
        return render_to_response(template, data, context_instance=RequestContext(request))

web_site/News/views.py
import json
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render_to_response, render
from django.template.context import RequestContext
from django.views.decorators.csrf import csrf_exempt
from django.views.decorators.http import require_POST
from django.contrib.auth.decorators import login_required
from web_site.News.models import NewsArticleImage, NewsArticle
from web_site.News.forms import NewsForm


@csrf_exempt
@require_POST
@login_required
def upload_photos(request):
    images = []
    for f in request.FILES.getlist("file"):
        obj = NewsArticleImage.objects.create(upload=f)
        images.append({"filelink": obj.upload.url})
    return HttpResponse(json.dumps(images), mimetype="application/json")


@login_required
def recent_photos(request):
    images = [
    {"thumb": obj.upload.url, "image": obj.upload.url}
        for obj in NewsArticleImage.objects.all().order_by("-date_created")[:20]
    ]
    return HttpResponse(json.dumps(images), mimetype="application/json")


@login_required
def add_news_item(request):
    """ Add a new news item """
    form = NewsForm()
    if request.method == 'POST':
        submit = request.POST.get('cancel', None)
        if submit:
            return HttpResponseRedirect('/account/news')
        else:
            form = NewsForm(request.POST, request.FILES)
            if form.is_valid():
                form.save()
                return HttpResponseRedirect('/account/news')
    template = 'account/news_admin.html'
    data = {
        'form': form,
    }

    return render_to_response(template, data, context_instance=RequestContext(request))


def displayNewsItems(request):
    news = NewsArticle.objects.all()
    template = 'news-homepage.html'
    data = {
        'news': news,
    }
    return render(request, template, data)

web_site/templates/_account_bar.html
{% load account_tags %}
<ul class="nav pull-right">
    {% if request.user.is_authenticated %}
        <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                {% user_display request.user %}
                <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
                <li><a href="{% url account_settings %}"><i class="icon-user icon-white"></i> Settings</a></li>
                <li><a href="{% url manage-artist-images %}"><i class="icon-picture icon-white"></i> Manage Images</a></li>
                <li><a href="{% url upload-artist-images %}"><i class="icon-plus icon-white"></i> Upload Images</a></li>
                <li class="divider"></li>
                <li><a href="{% url account_logout %}"><i class="icon-off icon-white"></i> Log out</a></li>
            </ul>
        </li>
    {% else %}
        <li><a href="{% url account_login %}">Log in</a></li>
        {% if ACCOUNT_OPEN_SIGNUP %}
            <li class="navbar-text">or</li>
            <li><a href="{% url account_signup %}">Sign up</a></li>
        {% endif %}
    {% endif %}
</ul>

web_site/templates/_community_gallery.html
{% block body %}
<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    
</div>

{% for event in events %}

		{% ifchanged event.title %} <div class="row span12"><hr> <h1 style="padding-bottom:15px" id="{{ event.title }}">{{ event.title }}</h1></div> {% endifchanged %}



				<div class="span12">{% autoescape off %} {{ event.description }}{% endautoescape %}</div>

		<br />
		<br />

			<div id="gallery-{{ event.pk }}" data-toggle="modal-gallery" data-target="#modal-gallery">

				{% for image in event.communitypicture_set.all %}
				<div class="span2"><a href="{{ MEDIA_URL }}{{ image.file }}" rel="gallery"><img class="thumbnail" src="{{image.file.url_125x125}}" alt=""></a></div>
				{% endfor %}
			</div>
	{% endfor %}	

	
{% endblock %}

web_site/templates/_footer.html
{% load i18n %}
<div class="legal">
</div>

web_site/templates/_press_gallery.html
{% block body %}
<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    
</div>

<!-- modal-gallery is the modal dialog used for the image gallery -->
<div id="modal-gallery" class="modal modal-gallery hide fade">
    <div class="modal-header">
        <a class="close" data-dismiss="modal">&times;</a>
        <h3 class="modal-title"></h3>
    </div>
    <div class="modal-body"><div class="modal-image"></div></div>
    <!-- <div class="modal-footer">
        <a class="btn btn-primary modal-next">Next <i class="icon-arrow-right icon-white"></i></a>
        <a class="btn btn-info modal-prev"><i class="icon-arrow-left icon-white"></i> Previous</a>
        <a class="btn btn-success modal-play modal-slideshow" data-slideshow="5000"><i class="icon-play icon-white"></i> Slideshow</a>
        <a class="btn modal-download" target="_blank"><i class="icon-download"></i> Download</a>
    </div> -->
</div>

<h1> blah of blah Press </h1>
<ul class="thumbnails">
	
	{% for article in articles %}

		{% ifchanged article.year %} <div class="row span12"><hr> <h3 style="padding-bottom:15px">{{ article.year }}</h3></div> {% endifchanged %}

		<li class="span3">
			<div class="thumbnail" id="gallery-{{ article.pk }}" data-toggle="modal-gallery" data-target="#modal-gallery">
				
				<a href="{{ MEDIA_URL }}{{article.thumbnail}}" rel="gallery" class="thumbnail"><img src="{{ MEDIA_URL }}{{article.thumbnail}}" alt="" id="{{ article.title }}"></a>
				
						{% for page in article.presspage_set.all %}
						<a href="{{ MEDIA_URL }}{{page.file}}" title="{{page.pgnumber}}" rel="gallery"></a>
						{% endfor %}
						<div class="caption" >
							<blockquote>
								<div><strong>{{article.title}}</strong></div>
								<div>{{article.publication}}</div>
								
							</blockquote>	
						</div>
			</div>
		</li>
	
{% endfor %}
</ul>

	
{% endblock %}

web_site/templates/account_template.html
{% extends "account/base.html" %}
{% load upload_tags %}


{% block head_title %}Account{% endblock %}

{% block body %}
<div class="container">

    <div class="page-header">
        <h1>Django Jquery file upload demo</h1>
    </div>
    


{% endblock %}

web_site/templates/article_admins.html
{% extends "account/base.html" %}
{% load upload_tags %}
{% load account_tags %}




{% block head_title %}Account{% endblock %}

{% block body %}
    {% if user.is_superuser %}
<div class="container">

    
        <legend>Manage Articles</legend>

<table class="table">
    <thead>
        <tr>
            <th><a href="/account/press/article/add/"><i class="icon-plus icon-white"></i></a></th>
            <th></th>
            <th></th>
            <th>Title</th>
            <th>Publication</th>
            <th>Year</th>
            <th>Thumbnail</th>
           
        </tr>
    </thead>
        <tbody>
            {% for article in object_list %}
            <tr>
                <td><a href="article/delete/{{article.pk}}"><i class="icon-remove icon-white"></i></a> </td>
                <td><a href="article/edit/{{article.pk}}"><i class="icon-edit icon-white"></i></a></td>
                <td><a href="/account/press/article/{{article.pk}}/pages"><i class="icon-picture icon-white"></i></a></td>
                <td>{{article.title}}</td>
                <td>{{article.publication}}</td>
                <td>{{article.year}}</td>
                <td><img src="{{article.thumbnail.url_250x250}}"></td>

                
            </tr>

            {% endfor %}
             
    </tbody>
</table>       

{% else %}

    <h1>You May have reached this page in error or you don't have access to this page</h1>

{% endif %}

</div>



{% endblock %}

web_site/templates/artist-homepage.html
{% extends "inner-banner_artist.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

    
    
{% endblock %}

web_site/templates/banner_base.html
{% extends "site_base.html" %}

{% load i18n %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}
        <div class="hero-unit well">
        <img src="{{ STATIC_URL }}img/SOG-panorama.jpg" class="shop-panorama">
        </div>
        
        <div class="row">
            <div class="span3">
            {% block column-1 %}
                <a href="/shop"><h3>blah blah</h3></a>
                <p>Founded in 2002, blah of blah is a professional tattoo shop
                with the highest standards for art and cleanliness. We are
                located at 221 blah blah in blah blah, blah. We are open 7 days
                a week and while traditional blah tattooing is our specialty, our staff is well versed in a variety of styles. Appointments are recommended but walk-ins are welcome too! Please take a minute to check out our portfolios! Thank you.</p>
                
                
            {% endblock %}
            </div>
            <div class="span3">
            {% block column-2 %}
                <a href="/product"><h3>Books</h3></a>
                
            {% endblock %}
            </div>
            <div class="span3">
            {% block column-3 %}
                
                
            {% endblock %}
            </div>
            <div class="span3">
            {% block column-4 %}
                <a href="/community"><h3>Community</h3></a>
                
                
            {% endblock %}
            </div>
        </div>
    </div>
{% endblock %}

web_site/templates/inner-banner_merchandise-item.html
{% extends "inner-site_base.html" %}

{% load i18n %}

{% block body_base %}
    <div class="container">
        {% include "_messages.html" %}

        
{% for item in object_list %}
	<div class="row">
		<div class="span6"><h2>{{ item.Name }}</h2></div>
	</div>
	<div class="row">
		<div class="span2"><img src="{{ item.PriImage.url }}"></div>
		<div class="row">
		<div class="span6">
			<p>{{ item.Description }}</p>
			<h4>Available at:</h4>
			{% for distributors in item.distributors.all %}
				
				<ul>
					<li>
						<a href="{{ distributors.URL }}">{{ distributors.Name }}</a>
					</li>
				</ul>


			{% endfor %}
		</div>
		</div>

	</div>
	<br />
	<br />
	<br />
	<div class="row">
		{% for image in item.productimage_set.all %}



			<img src="{{ image.file.url_250x250 }}" class="thumbnail span2">

		{% endfor %}
	</div>

    </div>
{% endfor %}
 
{% endblock %}

web_site/templates/merchandise-homepage.html
{% extends "inner-banner_merchandise.html" %}

{% load i18n %}

{% block head_title %}Books{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

    
    
{% endblock %}

web_site/templates/merchandise-item-homepage.html
{% extends "inner-banner_merchandise-item.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

    
    
{% endblock %}

web_site/templates/pages-homepage.html
{% extends "inner-banner_pages.html" %}

{% load i18n %}

{% block head_title %}{% trans "Welcome" %}{% endblock %}

{% block body_class %}home{% endblock %}

{% block banner %}

    
    
{% endblock %}

web_site/templates/site_base.html
{% extends "base.html" %}

{% load metron_tags %}
{% load i18n %}

{% block extra_head_base %}
    {% block extra_head %}{% endblock %}
{% endblock %}

{% block footer %}
    {% include "_footer.html" %}
{% endblock %}

{% block extra_body_base %}
    {% analytics %}
    {% block extra_body %}{% endblock %}
{% endblock %}